# Generated by Django 3.1.6 on 2021-02-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('threshold', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('summary', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
